# Generated by Django 5.2 on 2025-05-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_sample_courses_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='youtube_playlist_id',
            field=models.CharField(blank=True, help_text='YouTube playlist ID for course videos', max_length=100, null=True),
        ),
    ]
