# Generated by Django 5.2 on 2025-06-30 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='installment_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='installment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='users.feeinstallment'),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('payment', 'Payment Received'), ('enrollment', 'New Enrollment'), ('system', 'System Alert'), ('fee_due', 'Fee Due Alert'), ('installment_payment', 'Installment Payment')], max_length=20),
        ),
        migrations.CreateModel(
            name='StudentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('fee_reminder', 'Fee Reminder'), ('installment_due', 'Installment Due'), ('payment_success', 'Payment Success'), ('general', 'General')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('is_popup', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentInstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_payments', to='users.feeinstallment')),
                ('student_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_payments', to='users.studentfee')),
            ],
            options={
                'unique_together': {('student_fee', 'installment')},
            },
        ),
    ]
