# Generated by Django 5.2 on 2025-07-01 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_receipt_and_expiry'),
        ('users', '0025_adminnotification_installment_number_and_more'),
    ]

    operations = [
    ]
